### ISSUE TITLE
Unsure of how to use tool

### ISSUE THREAD

**Issue by incarne** [moosotc/dormin#2]
Hello, just trying to figure out the complete process of using this tool. I have the Nico.dat but im unsure of where to go from there. Any help is appreciated to get model files ^^

**Comment by moosotc** [comment]
incarne ***@***.***> writes:

> Hello, just trying to figure out the complete process of using this
> tool. I have the Nico.dat but im unsure of where to go from there. Any
> help is appreciated to get model files ^^
>

From within dormin directory

$ cd index
$ sh ./index.sh /path/to/the/directory/where/sotc.iso-is-mounted

This should create necessary indices. That said it's been a while since
i tried this last so i don't know whether it still works.

**Comment by incarne** [comment]
> incarne ***@***.***> writes:
> Hello, just trying to figure out the complete process of using this tool. I have the Nico.dat but im unsure of where to go from there. Any help is appreciated to get model files ^^
> From within dormin directory $ cd index $ sh ./index.sh /path/to/the/directory/where/sotc.iso-is-mounted This should create necessary indices. That said it's been a while since i tried this last so i don't know whether it still works.

Hey thanks for replying so fast! I'm pretty new to using tools like this. Is this initiated by powershell? 

Ive tried using powershell and receiving an error. Ive tried multiple combinations with and without the $, setting the 2nd line to where the ISO is mounted but same issue unfortunately:

PS C:\Users\Fabian\Desktop\Sotc\dormin-master> cd index
>> sh ./index.sh /C:\Users\Fabian\Desktop\Sotc
sh : The term 'sh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ sh ./index.sh /C:\Users\Fabian\Desktop\Sotc
+ ~~
    + CategoryInfo          : ObjectNotFound: (sh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by moosotc** [comment]
incarne ***@***.***> writes:

>> incarne ***@***.***> writes: Hello, just trying to figure out the
>> complete process of using this tool. I have the Nico.dat but im
>> unsure of where to go from there. Any help is appreciated to get
>> model files ^^ From within dormin directory $ cd index $ sh
>> ./index.sh /path/to/the/directory/where/sotc.iso-is-mounted This
>> should create necessary indices. That said it's been a while since i
>> tried this last so i don't know whether it still works.

[..]

Gotcha. Unfortunatelly I have only bad news: haven't touched (kept
up-to-date) dormin in years, so the code has somewhat bitrotted, nothing
too dramatic but requiring work. Thing is - ocaml itself has evolved in
a way that make some assumption in lablGL (the OpenGL bindings library
for OCaml) no longer true.

Other bit of bad news is that i don't have Windows and can't check
things. In the past people have packaged precompiled dormin with GUIs
but I only heard about those, never tried them myself, you can try
asking people who produced explaration videos on youtube whether they
have Windows binaries handy. I can't even (straightforwardly) build the
thing myself here on linux!

Hope you will find someone who whill be helpful, looking for people on
youtube might be your best bet. Sorry.

**Comment by incarne** [comment]
Hey no worries, appreciate you and hope youre doing well :)

**Comment by moosotc** [comment]
incarne ***@***.***> writes:

> Hey no worries, appreciate you and hope youre doing well :) 

This e-mail is mainly a reminder (to myself) of the current woes. The
introduction of immutable/safe string and mutable "bytes" in OCaml makes
things a bit more complex given that the central data access structure
in dormin a tuple "(int * string)" and its use is pervasive throughout
the code-base. Switching over to using bytes is mostly trivial, but does
require some care. Second problem is lablGL+GLUT - there are variety of
not so obvious problems with it (for instance this is the reason why
llpp switched over to using home grown Wsi abstractin layer instead of
GLUT).

Addressing the first problem (safe string) is mostly boring string
search and replace affair and, i think, i did just that in a matter of
tens of minutes today. lablGL OTOH is harder problem that i just can not
force myself to do. so that's that - the inner engine driving Dormin
works, with superficial changes, the user facing parts and OpenGL
interaction, surprisingly, does not.

It looks as if writing something that exports some Blender consumable
output out of SotC internal data is the most productive thing to do, but
it also looks as if I alone will not do it (Files inside reeng/
directory contains best i could come up with documentation wise, the
rest can be derived from ocaml/c code in the main directory)
